Webit\Bundle\PHPCRToolsBundle\Document\Generic:
  properties:
    parentId:
      type: string
      groups: [generic]
      serialized_name: parentId
  callback_methods:
    pre_serialize: [getParentId]
